update

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -27,12 +27,20 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - name: Build
+      - name: Build and test
         shell: bash
         run: |
           brew install zlib-ng libspng llvm
           cmake -B build -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S .
           cmake --build build --config Release
           build/test
-          bash -c "shopt -s nullglob; for file in CI_TEST-*.png; do cmp $file CI_TEST.png; if [ \$? -ne 0 ]; then echo 'fail at: cmp $file CI_TEST.png'; exit 1; fi; done; shopt -u nullglob;"
+          shopt -s nullglob
+          for file in CI_TEST-*.png; do
+            cmp $file CI_TEST.png
+            if [ \$? -ne 0 ]; then
+              echo 'fail at: cmp $file CI_TEST.png'
+              exit 1
+            fi
+          done
+          shopt -u nullglob
 
